version: "3"

services:
  voucher-rest:
    image: postgres
    ports:
      - 5433:5432
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRES_DB=postgres
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASS}
